# Generated by Django 2.2.5 on 2019-09-22 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetsapp', '0007_delete_expense'),
        ('expensesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='budgetsapp.Budget')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expensesapp.Expense')),
            ],
            options={
                'unique_together': {('budget', 'expense')},
            },
        ),
    ]
