# Generated by Django 2.2.5 on 2019-09-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0002_budgetexpense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetExpense',
        ),
    ]
