# Generated by Django 3.1.4 on 2021-06-01 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investmentapp', '0002_auto_20210601_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='invest',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invest',
            name='initial_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invest',
            name='factor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='factor', to='investmentapp.conversion'),
            preserve_default=False,
        ),
    ]
