# Generated by Django 2.2.5 on 2019-10-03 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetsapp', '0007_delete_expense'),
        ('categoriesapp', '0003_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budgetsapp.Budget'),
        ),
    ]
