# Generated by Django 2.2.5 on 2019-10-03 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesapp', '0004_category_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='budget',
        ),
    ]
