# Generated by Django 2.2.6 on 2020-03-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffeeName', models.CharField(max_length=100)),
                ('coffeeDescription', models.CharField(blank=True, default='', max_length=255)),
                ('coffeeIntensity', models.PositiveIntegerField(default=1)),
                ('isRistretto', models.BooleanField(default=False)),
                ('isEspresso', models.BooleanField(default=False)),
                ('isLungo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Coffees',
            },
        ),
    ]
