# Generated by Django 2.2.5 on 2019-09-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
