# Generated by Django 2.2.5 on 2019-09-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetsapp', '0002_auto_20190920_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
