# Generated by Django 2.2.5 on 2019-09-21 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetsapp', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='budgetsapp.Budget'),
            preserve_default=False,
        ),
    ]
