# Generated by Django 2.2.5 on 2019-09-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetsapp', '0005_auto_20190921_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='gasto',
            field=models.BooleanField(default=True),
        ),
    ]
