# Generated by Django 2.2.5 on 2019-09-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetsapp', '0006_expense_gasto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
